name: Test

'on':
  push:
    branches:
      - "**"
    paths-ignore:
    - Changes
    - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
    - Changes
    - '**.md'
  schedule:
    - cron: '17 8 5 * *'
  workflow_dispatch:

env:
  AUTHOR_TESTING: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl_version:
          - latest
          - "5.34"
          - "5.30"
          - "5.24"

    steps:
      - uses: actions/checkout@v3

      - uses: shogo82148/actions-setup-perl@v1
        with:
         perl-version: ${{ matrix.perl_version }}

      - run: cpm install --show-build-log-on-failure Dist::Zilla

      - run: dzil authordeps --missing | cpm install --show-build-log-on-failure -

      - run: dzil listdeps --missing | cpm install --show-build-log-on-failure -

      - run: dzil test
